hosts:
  - sonarqube-stg.swire.io

protocols:
  http:
    enabled: true
    port: 80
    httpsRedirect: true

  https:
    enabled: true
    port: 443

tls:
  enabled: true
  mode: SIMPLE
  dnsNames: 
  - sonarqube-stg.swire.io
  issuerName: "letsencrypt-prod-cluster"

destionationrule:
  enabled: false

virtualservice:
  enabled: true


gateway:
  enabled: true

virtualservice:
  enabled: true
  namespace: "l1-web-sonarqube"

  http:
  - match:
      - uri:
          prefix: /
    route:
      - destination:
          host: sonarqube-sonarqube
          port:
            number: 9000
    
  tls: {}