# hosts:
#   - mydns.com

#   https:
#     enabled: true
#     port: 443

tls:
  enabled: false
  mode: SIMPLE
  dnsNames: 
  - mydns.com
  issuerName: "letsencrypt-prod-cluster"

destionationrule:
  enabled: false

gateway:
  enabled: true
  rules:
    - name: test
      protocols:
        http:
          enabled: true
          port: 80
          httpsRedirect: true
        https:
          enabled: true
          port: 443
          tls:
            mode: SIMPLE
            dnsNames: 
            - mydns.com
            issuerName: "letsencrypt-prod-cluster"

      hosts:
      - mydns.com


virtualservice:
  enabled: false
  rules:
    - name: test1
      gatewayName: test1
      hosts: 
      - mydns.com
      namespace: "l1-web-deptrack"

      http:
      - match:
          - uri:
              prefix: /api
        route:
          - destination:
              host: apiserver
              port:
                number: 80
      - match:
          - uri:
              prefix: /
        route:
          - destination:
              host: frontend
              port:
                number: 80
        
      tls: {}
    - name: test
      gatewayName: test
      hosts: 
      - myseconddns.com
      namespace: "l1-web-deptrack"

      http:
      - match:
          - uri:
              prefix: /api
        route:
          - destination:
              host: apiserver
              port:
                number: 80
      - match:
          - uri:
              prefix: /
        route:
          - destination:
              host: frontend
              port:
                number: 80
        
      tls: {}